{
 "title": "SLO /  SLI Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(django_http_responses_total_by_status_total{status!~\"4..\"}[1h]))\n/\nsum(rate(django_http_responses_total_by_status_total[1h]))) * 100",
     "legendFormat": "Admin App"
    },
    {
     "expr": "(sum(rate(app_request_count_total{http_status!~\"4..\"}[1h]))\n/\nsum(rate(app_request_count_total[1h]))) * 100",
     "legendFormat": "Main App"
    }
   ]
  },
  {
   "title": "Error Budget left in % [1h]",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(rate(django_http_responses_total_by_status_total{status!~\"4..\"}[1h]))/sum(rate(django_http_responses_total_by_status_total[1h]))) - 0.95) * 60 * 60)",
     "legendFormat": "Admin App"
    },
    {
     "expr": "(((sum(rate(app_request_count_total{http_status!~\"4..\"}[1h]))/sum(rate(app_request_count_total[1h]))) - 0.95) * 60 * 60)",
     "legendFormat": "Main App"
    }
   ]
  },
  {
   "title": "Percentage of requests - Admin",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"0.5\"}[1h])) / sum(rate(django_http_requests_latency_seconds_by_view_method_count[1h])) * 100",
     "legendFormat": "within 500ms"
    },
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"1.0\"}[1h])) / sum(rate(django_http_requests_latency_seconds_by_view_method_count[1h])) * 100",
     "legendFormat": "within 1s"
    }
   ]
  },
  {
   "title": "Percentage of requests - Flask",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_bucket{le=\"0.5\"}[1h])) / sum(rate(app_request_latency_seconds_count[1h])) * 100",
     "legendFormat": "within 500ms"
    },
    {
     "expr": "sum(rate(app_request_latency_seconds_bucket{le=\"1.0\"}[1h])) / sum(rate(app_request_latency_seconds_count[1h])) * 100",
     "legendFormat": "within 1s"
    }
   ]
  },
  {
   "title": "Availability - Admin ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(sum(rate(django_http_responses_total_by_status_total{status!~\"4..\"}[1h]))\n/\nsum(rate(django_http_responses_total_by_status_total[1h]))) * 100",
     "legendFormat": "Admin App"
    },
    {
     "expr": "(sum(rate(app_request_count_total{http_status!~\"4..\"}[1h]))\n/\nsum(rate(app_request_count_total[1h]))) * 100",
     "legendFormat": "Main App"
    }
   ]
  },
  {
   "title": "Percentage of requests - Flask",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_bucket{le=\"0.5\"}[1h])) / sum(rate(app_request_latency_seconds_count[1h])) * 100",
     "legendFormat": "within 500ms"
    }
   ]
  },
  {
   "title": "Percentage of requests - Admin",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{le=\"0.5\"}[1h])) / sum(rate(django_http_requests_latency_seconds_by_view_method_count[1h])) * 100",
     "legendFormat": "within 500ms"
    }
   ]
  },
  {
   "title": "Admin - % of time with (Latency <500ms ) < 90% [1h]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(latency500_time[1h]) * 15) /36"
    }
   ]
  },
  {
   "title": "Admin - % of time with Error ratio < 1% [1h]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(error_time[1h]) * 15)/36"
    }
   ]
  },
  {
   "title": "Admin [90% <500ms, Error ratio <1%] [15m]]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "45 - (900 - sum_over_time(error_500_time[15m]) * 15)",
     "legendFormat": "Error Budget (seconds) [15m]"
    },
    {
     "expr": "(sum_over_time(error_500_time[15m]) * 15) / 9",
     "legendFormat": "Availability (%) [15m]"
    }
   ]
  }
 ]
}